### ISSUE TITLE
task: have pages link to each other page

### ISSUE THREAD

**Issue by Mooseonce** [cse442-fall-2019-offering/442projects-matthew-hertz-fan-club#15]

**Comment by tdvoisic** [comment]
I updated the tracking page and added a navigation bar that links to 3 other html pages. In the branch tracking-with-navigation-bar

**Comment by Joeyglick** [comment]
Task Test:
(1) Upon opening the website, there are clearly different tabs on the top left
(2) User has the ability to switch between tabs by clicking on the name of the tab
(3) If a user can click between the different tabs, test passed

**Comment by Joeyglick** [comment]
QA test:
was able to run through the task test successfully, test passed.
