### ISSUE TITLE
Blog post functionality - save posts to .txt files (for use as placeholder database)

### ISSUE THREAD

**Issue by willlenore** [cse442-fall-2019-offering/442projects-matthew-hertz-fan-club#18]
Save user inputted title and post to a .txt file, as a placeholder until we get the database set up.

**Comment by Joeyglick** [comment]
Task Test:
(1) The previous test about blog post passed 
(2) After user posts a blog has to option to save the post
(3) After saving, the post is then saved as a .txt file

**Comment by willlenore** [comment]
Update: Saving post to .txt file was meant to be an intermediate task until the SQL database was ready to go. It turns out saving the text to a .txt file is a convoluted process, and since it wasn't the end goal,  I instead edited the layout of the blog page instead and have information on how to save the posts to the database.
