### ISSUE TITLE
Blog post functionality - blog posts are saved to database and can be read later on

### ISSUE THREAD

**Issue by willlenore** [cse442-fall-2019-offering/442projects-matthew-hertz-fan-club#24]
Blog posts will be saved into the database so they can be accessed at a later date. This task is a follow up to a previous assigned to me that was impractical, so I changed it.

**Comment by Joeyglick** [comment]
Task Test
(1) Open website and go to Blog page
(2) Click add and input information to appropriate fields
(3) Click add and see blog post posted
(4) If you can see previous blog post after clicking title of post on right side, test passed

**Comment by willlenore** [comment]
Progress on this week's task - I have begun doing research into saving the blog posts to the database for a certain login. The links below will help me to write the necessary functions this week:

https://jwcooney.com/2012/06/19/how-to-query-sql-server-system-tables-for-text-in-stored-procedures/

https://bootes.co/Technical-Notes/How-To-Retrieve-Data-From-a-SQL-Server-Table-Into-An-HTML-Page-Using-A-WebMethod-JavaScript-JQuery-AJAX-And-ASPNET

https://stackoverflow.com/questions/15251095/display-data-from-sql-database-into-php-html-table

https://www.siteground.com/tutorials/php-mysql/display-table-data/
